// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using CoreAPI.Models;

namespace CoreAPI.Models
{
    public partial class ispanMsit145shiba
    {

        [DbFunction("udf_get_serialno", "dbo")]
        public static string udf_get_serialno()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
