// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreAPI.Models
{
    public partial class OrderItems
    {
        public int? OrderFid { get; set; }
        public string ItemId { get; set; }
    }
}