// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreAPI.Models
{
    public partial class Products
    {
        public int Fid { get; set; }
        public int BFid { get; set; }
        public string ProductName { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? Qty { get; set; }
        public int? CategoryFid { get; set; }
        public string Memo { get; set; }
        public string MenuFid { get; set; }
        public string IsForSale { get; set; }
    }
}