// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreAPI.Models
{
    public partial class ProductOptions
    {
        public int Fid { get; set; }
        public string OptionName { get; set; }
        public int? OptionGroupFid { get; set; }
        public int? BFid { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? Qty { get; set; }
    }
}